### ISSUE TITLE
Document default behaviour for missing message implementations

### ISSUE THREAD

**Issue by sjeps** [iboB/dynamix#1]
Very nice library!
As i can see the usual behaviour for calling a message to a mixin that does not implement it is throwing an exception, wich is nice.

As an alternative i can define
`DYNAMIX_NO_MSG_THROW`

to trigger assertions instead.

What about an option to simply doing nothing in the case the message is not implemented?

That could be compilation unit defined or mixin defined or "interface" defined.

That would be helpful in calling a message for each element of a vector of objects of wich only some implements a certain interface.

(Try-catching would be time wasteful)

**Comment by iboB** [comment]
This is actually possible, but it's not yet documented. An example usage can be found in test for the functionality here: https://github.com/iboB/dynamix/blob/master/test/msg_default_impl.cpp

Check out the default implementations at the bottom. Instead of using the macro `DYNAMIX_DEFINE_MESSAGE` you need to use `DYNAMIX_DEFINE_MESSAGE_<N>_WITH_DEFAULT_IMPL` just like when you were declaring the message and then just write the implementation in a block underneath. In this block you can do nothing or *something* :) `dm_this` is valid in said block.

I'm keeping the issue open, since this needs to be documented.
